### ISSUE TITLE
ResolutionError

### ISSUE THREAD

**Issue by cissoidx** [numba/numba-examples#12]
hello, guys. I followed the instructions and got this error:
pkg_resources.ResolutionError: Script 'scripts/numba_bench' not found in metadata

Anyone have encountered this same error?

**Comment by sklam** [comment]
The error is new to me. I just tried running:

```bash
git clone https://github.com/numba/numba-examples
cd numba-examples
conda create -n numba_bench --file conda-requirements.txt
source activate numba_bench
python setup.py install
numba_bench -o results
```
It all runs fine on my Mac.

Can you tell us which platform you are running on? Also, a full traceback would be helpful as well.

**Comment by cissoidx** [comment]
I work on Ubuntu 16.04. I tried this again but in vain. Here is the traceback(~ replaced my home directory):

Traceback (most recent call last):
  File "~/anaconda3/bin/numba_bench", line 4, in <module>
    __import__('pkg_resources').run_script('numba-bench==0.1', 'numba_bench')
  File "~/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "~/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/numba_bench' not found in metadata at '~/repo/demos/numba-examples/numba_bench.egg-info'
